apiVersion: v1
kind: Service
metadata:
  name: k8sdocker-service
spec:
  selector:
    app: k8sdocker
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer